---
# tasks file for haproxy-custom
- name: install dependencies
  dnf:
          name: "{{item}}"
          state: present
  with_items: "{{ haproxy_dependency }}"

- name: Download haproxy
  get_url:
          url: https://www.haproxy.org/download/2.6/src/haproxy-2.6.1.tar.gz
          dest: /tmp/

- name: extract packages
  unarchive:
          src: /tmp/haproxy-2.6.1.tar.gz
          dest: /tmp/
          remote_src: yes

- name: create user for Haproxy
  user:
          name: haproxy
          state: present
          system: yes
          create_home: False
          shell: /sbin/nologin

- name: Compilation and installation 
  shell:
          chdir: /tmp/haproxy-2.6.1
          cmd: "make -j 4 TARGET=linux-glibc USE_OPENSSL=1 USE_ZLIB=1 USE_PCRE=1 USE_SYSTEMD=1 && make install PREFIX=/usr/local/haproxy"
  register: compile_info
  failed_when: compile_info.rc != 0

- name: Create a symbolic link
  file:
          src: /usr/local/haproxy/sbin/haproxy
          dest: /usr/sbin/haproxy
          state: link

- name: configure haproxy as a service
  template:
          src: haproxy.service.j2
          dest: /usr/lib/systemd/system/haproxy.service

- name: reload daemon
  systemd:
    daemon_reload: yes
  tags: reload

- name: create conf directory
  file:
          path: "{{item}}"
          state: directory
          mode: "0755"
  with_items:
          - /etc/haproxy
          - /var/lib/haproxy/dev

- name: coping Haproxy.cfg
  template:
          src: haproxy.cfg.j2
          dest: /etc/haproxy/haproxy.cfg
          validate: haproxy -c -f %s
  tags: valid

- name: start haproxy  
  systemd:
          name: "{{item}}"
          state: started
          enabled: yes
  with_items:
          - haproxy
          - rsyslog
  tags: start

- name: rsyslog configuration of haproxy
  template:
          src: haproxy-syslog.conf.j2
          dest: /etc/rsyslog.d/99-haproxy.conf
  tags: copy1

- name: restart service
  service:
          name: rsyslog
          state: restarted


